config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'onepage/index'
  root to: "onepage#index", as: 'home'



 get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'



  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile/:id/edit', to: 'users#edit', as: 'update_profile'
  patch '/profile/:id/edit', to: 'users#update', as: 'user'



  get '/workouts' => 'workouts#index', as: 'workouts'
  get '/workouts/new' => 'workouts#new', as: 'new_workout'
  post '/workouts' => 'workouts#create'
  get '/workout/:id/edit', to: 'workouts#edit', as: 'update_workout'
  patch '/workouts/:id', to: 'workouts#update'

  get '/workouts/:id' => 'workouts#show' , as: 'workout'
  delete '/workouts/:id' => 'workouts#destroy'




  get '/meals' => 'meals#index', as: 'meals'
  get '/meals/new' => 'meals#new', as: 'new_meal'
  post '/meals' => 'meals#create'

   get '/meal/:id/edit', to: 'meals#edit', as: 'update_meal'
  patch '/meals/:id', to: 'meals#update'

  get '/meals/:id' => 'meals#show' , as: 'meal'
  delete '/meals/:id' => 'meals#destroy'




  get '/tips' => 'tips#index', as: 'tips'
  get '/tips/new' => 'tips#new', as: 'new_tip'
  post '/tips' => 'tips#create'
  get '/tips/:id/edit', to: 'tips#edit', as: 'update_tip'
  patch '/tips/:id', to: 'tips#update'


  get '/tips/:id' => 'tips#show' , as: 'tip'
  delete '/tips/:id' => 'tips#destroy'






#   get '/meals/:id/bookings/new'=> 'bookings#new' ,as:'new_booking'
#   get '/meals/:id/edit' => 'meals#edit', as: 'edit_meal'
#   patch '/meals/:id' => 'meals#update'
#   delete '/meals/:id' => 'meals#destroy'


#   get '/users' => 'users#index', as: 'users'
#   get '/users/new' => 'users#new', as: 'new_user'
#   post '/users' => 'users#create'
#   get '/users/:id' => 'users#show' , as: 'user'
#   get '/users/:id/edit' => 'users#edit', as: 'edit_user'
#   patch '/users/:id' => 'users#update'
#   delete '/users/:id' => 'users#destroy'


#   get 'users/:id', to: 'users#show_profile'
#   get 'users/:id/edit', to: 'users#edit'
#   put 'profile', to: 'users#update', as: 'update_profile'
#   get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
#   get '/profile', to: 'users#show_profile', as: 'profile'







#   get '/bookings' => 'bookings#index', as: 'bookings'
#   post '/cars/:id/bookings' => 'bookings#create'
#   get '/bookings/:id' => 'bookings#show' , as: 'booking'
#   get '/bookings/:id/edit' => 'bookings#edit', as: 'edit_booking'
#   patch '/bookings/:id' => 'bookings#update'
#   delete '/bookings/:id' => 'bookings#destroy', as: 'return_booking'



#   get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'

#   get '/contactus' => 'ourcontacts#index' ,  as: 'contactus'

# get '/customers/:customer_id/bookings' => 'bookings#index', as: 'bookings_customers'
# post '/bookings/:id' => 'bookings#update'
# #post '/customers/:customer_id/bookings' => 'bookings#update'

# end

#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   belongs_to :user
   belongs_to :workout_category
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user
  helper_method :group_by_day


  def index

    @workouts = Workout.where(user_id: current_user.id).order(date: :desc)





     # @exercise = @workouts.workout_category.description



    # @workouts = Workout.where(user_id: params[:user_id] )

    # @type = @workouts.type
    # @description = @workouts.description
    # @date = @workouts.date
  end

  def new
    @workouts = Workout.all
    @workout_categories = WorkoutCategory.all



  end

  def create
    foobar = workout_params()

    @workout = Workout.new(foobar)
    @workout.user = current_user
     # Pass in a date
      #if (customer_params[:lisence_expiry].to_date >  Date.today+14.days)


    if @workout.save
      redirect_to @workout
      else
        #byebug
      render 'new'
  end

end


  def show
  @workout_categories = WorkoutCategory.all
  @workout = Workout.find(params[:id])
  @exercise = @workout.workout_category.description

  puts "============="
  puts "============="
  puts @workout
  puts "============="
  puts "============="


  end


  def edit

    @workout = Workout.find(params[:id])
     @workout.user = current_user
     @workout_categories = WorkoutCategory.all

  end

  def update

    @workout = Workout.find(params[:id])

    redirect_to workout_path if @workout.update(workout_params)
  end


  def destroy

  @workout = Workout.find(params[:id])

         @workout.destroy
         redirect_to workouts_path

  end

  private
    def check_user
      if !current_user
        redirect_to home_path
      end
    end

    def workout_params
      params.require(:workout).permit(:workout_category_id, :description, :date)
    end


    def group_by_day(obj)
      sort_by_day = -> ( d ) {d.start.strftime("%A, %b %d %y")}
      return obj.group_by(&sort_by_day)
    end


end

app/views/workouts/edit.html.erb
<body class="workouteditbody">
	<div class="container">
<h1 class="workouteditheading">Edit Workout</h1>
<div class="workouteditform">
<%= form_with scope: :workout, model: @workout, local: true do |form| %>

  <p>
    <strong><%= form.label :type %><br></strong>
    <%= form.collection_select :workout_category_id, @workout_categories, :id, :description %>
  </p>

  <p>
    <strong><%= form.label :description %><br></strong>
    <%= form.text_area :description %>
  </p>

   <p>
    <strong><%= form.label :date %><br></strong>
    <%= form.date_field :date %>
  </p>


  <p>
    <%= form.submit class: "btn btn-dark"%>
  </p>

<% end %>
</div>

<div class ="backbutton">
<%= button_to 'Back', workout_path , method: :get, class:"btn btn-dark" %>
</div>
</div>
</body>

app/views/workouts/index.html.erb
<body class="workoutindexbody">
	<div class="container">
			<h1 class="workoutheading">Workout Lists</h1>

			<%= button_to "Add workouts", new_workout_path, method: :get, class: "btn btn-dark" %>

			<div class="workouttext">
					<table class="table table-dark">
						<thead>
		   				<tr>
					      <th scope="col">Workout Day</th>
					      <th scope="col">Description</th>
					      <th scope="col">Date</th>
		      		</tr>
		  			</thead>
			  		<tbody>
			    		<% @workouts.each do |workout| %>
								<tr>
						   		<td><%= workout.workout_category.description %></td>
						   		<td><%= workout.description %></td>
				     			<td><%= workout.date %></td>
				      		<td><button class="buttontextmeal"><%= link_to 'Details', workout_path(workout) , class: "btn btn-white" %></button></td>
				    		</tr>
							<% end %>
						</tbody>
					</table>
			</div>
	</div>
</body>

app/views/workouts/new.html.erb
<body class="workoutnewbody">
	<div class="container">

<h1 class="workoutnewheading">Enter Exercises</h1>
<div class="workouteditform">

<%= form_with scope: :workout, url: workouts_path, local: true do |form| %>
  <p>
  <strong><%= form.label :type %></strong><br>
  <%= form.collection_select :workout_category_id, @workout_categories, :id, :description %>
  </p>

  <p>
    <strong><%= form.label :description %></strong><br>
    <%= form.text_area :description %>
  </p>


  <p>
    <strong><%= form.label :date %></strong><br>
    <%= form.date_field :date %>

  </p>


	<p>
	  <%= form.submit class: "btn btn-dark"%>
	</p>

<% end %>
</div>
<div class ="backbutton">
<%= button_to 'Back', workouts_path , method: :get, class:"btn btn-dark" %>
</div>
</div>
</body>

app/views/workouts/show.html.erb
<body class="workoutshowbody">
	<div class = "container">

		<p class="workouttext">
		  <strong>Type:</strong>
		  <%= @exercise.capitalize %>

		</p>

		<p class="workouttext">
		  <strong>Description</strong>
		  <%= @workout.description %>
		</p>

		<p class="workouttext">
		  <strong>Date: </strong>
		  <%= @workout.date %>
		</p>


		<br/>
		<div class ="workoutprofilebutton">
		<div class ="row-md">


		<div class ="column-md , profilesubbutton">


		<button class="btn btn-dark"><%= link_to 'Edit', update_workout_path , class:"buttontext" %></button>



		<button class="btn btn-dark"><%= link_to 'Home', home_path , class:"buttontext" %></button>

		<button class="btn btn-dark"><%= link_to 'Back', workouts_path , class:"buttontext" %></button>



		<button class="btn btn-dark"><%= link_to 'Delete', workout_path,
		        method: :delete,
		        data: { confirm: 'Are you sure?' }  , class:"buttontext" %></button>

	</div>
	</div>
	</div>
	</div>
	</div>
</body>