config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'onepage/index'
  root to: "onepage#index", as: 'home'



 get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'



  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile/:id/edit', to: 'users#edit', as: 'update_profile'
  patch '/profile/:id/edit', to: 'users#update', as: 'user'



  get '/workouts' => 'workouts#index', as: 'workouts'
  get '/workouts/new' => 'workouts#new', as: 'new_workout'
  post '/workouts' => 'workouts#create'
  get '/workout/:id/edit', to: 'workouts#edit', as: 'update_workout'
  patch '/workouts/:id', to: 'workouts#update'

  get '/workouts/:id' => 'workouts#show' , as: 'workout'
  delete '/workouts/:id' => 'workouts#destroy'




  get '/meals' => 'meals#index', as: 'meals'
  get '/meals/new' => 'meals#new', as: 'new_meal'
  post '/meals' => 'meals#create'

   get '/meal/:id/edit', to: 'meals#edit', as: 'update_meal'
  patch '/meals/:id', to: 'meals#update'

  get '/meals/:id' => 'meals#show' , as: 'meal'
  delete '/meals/:id' => 'meals#destroy'




  get '/tips' => 'tips#index', as: 'tips'
  get '/tips/new' => 'tips#new', as: 'new_tip'
  post '/tips' => 'tips#create'
  get '/tips/:id/edit', to: 'tips#edit', as: 'update_tip'
  patch '/tips/:id', to: 'tips#update'


  get '/tips/:id' => 'tips#show' , as: 'tip'
  delete '/tips/:id' => 'tips#destroy'






#   get '/meals/:id/bookings/new'=> 'bookings#new' ,as:'new_booking'
#   get '/meals/:id/edit' => 'meals#edit', as: 'edit_meal'
#   patch '/meals/:id' => 'meals#update'
#   delete '/meals/:id' => 'meals#destroy'


#   get '/users' => 'users#index', as: 'users'
#   get '/users/new' => 'users#new', as: 'new_user'
#   post '/users' => 'users#create'
#   get '/users/:id' => 'users#show' , as: 'user'
#   get '/users/:id/edit' => 'users#edit', as: 'edit_user'
#   patch '/users/:id' => 'users#update'
#   delete '/users/:id' => 'users#destroy'


#   get 'users/:id', to: 'users#show_profile'
#   get 'users/:id/edit', to: 'users#edit'
#   put 'profile', to: 'users#update', as: 'update_profile'
#   get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
#   get '/profile', to: 'users#show_profile', as: 'profile'







#   get '/bookings' => 'bookings#index', as: 'bookings'
#   post '/cars/:id/bookings' => 'bookings#create'
#   get '/bookings/:id' => 'bookings#show' , as: 'booking'
#   get '/bookings/:id/edit' => 'bookings#edit', as: 'edit_booking'
#   patch '/bookings/:id' => 'bookings#update'
#   delete '/bookings/:id' => 'bookings#destroy', as: 'return_booking'



#   get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'

#   get '/contactus' => 'ourcontacts#index' ,  as: 'contactus'

# get '/customers/:customer_id/bookings' => 'bookings#index', as: 'bookings_customers'
# post '/bookings/:id' => 'bookings#update'
# #post '/customers/:customer_id/bookings' => 'bookings#update'

# end

#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



         has_many :workouts
         has_many :meals


  after_commit :update_user_name, on: :create
    def update_user_name
      user = User.last
      user.update(name: user.email.to_s.split('@')[0])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user
  helper_method :group_by_day


  def show
    # @user = User.find(params[:id])
    # @user = User.find_by_id(params[:id])
    # @user= current_user
    # @user = User.where(id: params [:id])
    @user = User.find(params[:id])
    puts "=============="
    puts "=============="
    puts @user
    puts @user.weight
    puts "=============="
    puts "=============="

    @weight = @user.weight
    @height = @user.height

    if @weight && @height

    @bmi = (10000*(@weight/(@height*@height))).round(2)
    @protein = (0.8*@weight).round(2)

    else

    @bmi = 0
    @protein = 0

    end


    @date = Date.today

    @updateddate = @user.updated_at
    puts "================="
    puts "================="
    puts "================="
    puts @user
    puts @updateddate
    puts @time
    puts "================="
    puts "================="
    puts "================="

  end

  def edit
      @user = current_user
  end

  def update
    @user = current_user
    @weight = @user.weight
    @height = @user.height

    puts "================="
    puts "================="
    puts "================="
    puts @user
    puts @weight
    puts @height
    puts "================="
    puts "================="
    puts "================="

    redirect_to profile_path if current_user.update(user_params)
  end

  private
    def check_user
      if !current_user
        redirect_to home_path
      end
    end

    def user_params
      params.require(:user).permit(:name, :weight, :height)
    end

    def group_by_day(obj)
      sort_by_day = -> ( d ) {d.start.strftime("%A, %b %d %y")}
      return obj.group_by(&sort_by_day)
    end



end

app/views/users/edit.html.erb
<body class="profileeditbody">
	<div class="container">
<h2 class="profileeditheading">


<strong>Edit Profile</strong>


</h2>
<div class="customereditform">
<%= form_with scope: :user, model: @user, local: true do |form| %>

  <p>
    <strong><%= form.label :name %><br></strong>
    <%= form.text_field :name %>
  </p>

  <p>
    <strong><%= form.label :height %><br></strong>
    <%= form.text_field :height %>
  </p>

  <p>
    <strong><%= form.label :weight %><br></strong>
    <%= form.text_field :weight %>
  </p>

  <p>
    <%= form.submit class: "btn btn-dark"%>
  </p>

<% end %>
</div>
<div class ="backbutton">
<%= button_to 'Back', home_path , method: :get, class:"btn btn-dark" %>
</div>
</div>
</body>

app/views/users/show.html.erb
<body class="userbody">
	<div class = "container">

	<div class = "profilebody">




		<h2 class="biometrictext">

		  <strong>Biometrics</strong>

		 </h2>

		<p class="usertext">


		  <strong>Name:</strong>

		  <%= @user.name.capitalize %>

		</p>

		<p class="usertext">
		  <strong>Height</strong>
		    <%= @user.height.to_s + "cm" %>
		</p>

		<p class="usertext">
		  <strong>Weight:</strong>
		    <%= @user.weight.to_s + "kg" %>
		</p>



		<p class="usertext">
		  <strong>Body Mass Index:</strong>
		  <%=@bmi %>
		</p>


		<p class="usertext">
		  <strong>Daily Protein Intake:</strong>
		  <%=@protein.to_s + "g"%>
		</p>


		<p class="usertext">
		  <strong>Updated as of: </strong>


		  <%=@updateddate.strftime("%m/%d/%Y")  %>
		</p>



		<button class="btn btn-dark"><%= link_to 'Edit', update_profile_path , class:"buttontext" %></button>


					<div class ="backbutton">
			<%= button_to 'Back', home_path , method: :get, class:"btn btn-dark" %>
			</div>



	</div>
</body>