config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'onepage/index'
  root to: "onepage#index", as: 'home'



 get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'



  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile/:id/edit', to: 'users#edit', as: 'update_profile'
  patch '/profile/:id/edit', to: 'users#update', as: 'user'



  get '/workouts' => 'workouts#index', as: 'workouts'
  get '/workouts/new' => 'workouts#new', as: 'new_workout'
  post '/workouts' => 'workouts#create'
  get '/workout/:id/edit', to: 'workouts#edit', as: 'update_workout'
  patch '/workouts/:id', to: 'workouts#update'

  get '/workouts/:id' => 'workouts#show' , as: 'workout'
  delete '/workouts/:id' => 'workouts#destroy'




  get '/meals' => 'meals#index', as: 'meals'
  get '/meals/new' => 'meals#new', as: 'new_meal'
  post '/meals' => 'meals#create'

   get '/meal/:id/edit', to: 'meals#edit', as: 'update_meal'
  patch '/meals/:id', to: 'meals#update'

  get '/meals/:id' => 'meals#show' , as: 'meal'
  delete '/meals/:id' => 'meals#destroy'




  get '/tips' => 'tips#index', as: 'tips'
  get '/tips/new' => 'tips#new', as: 'new_tip'
  post '/tips' => 'tips#create'
  get '/tips/:id/edit', to: 'tips#edit', as: 'update_tip'
  patch '/tips/:id', to: 'tips#update'


  get '/tips/:id' => 'tips#show' , as: 'tip'
  delete '/tips/:id' => 'tips#destroy'






#   get '/meals/:id/bookings/new'=> 'bookings#new' ,as:'new_booking'
#   get '/meals/:id/edit' => 'meals#edit', as: 'edit_meal'
#   patch '/meals/:id' => 'meals#update'
#   delete '/meals/:id' => 'meals#destroy'


#   get '/users' => 'users#index', as: 'users'
#   get '/users/new' => 'users#new', as: 'new_user'
#   post '/users' => 'users#create'
#   get '/users/:id' => 'users#show' , as: 'user'
#   get '/users/:id/edit' => 'users#edit', as: 'edit_user'
#   patch '/users/:id' => 'users#update'
#   delete '/users/:id' => 'users#destroy'


#   get 'users/:id', to: 'users#show_profile'
#   get 'users/:id/edit', to: 'users#edit'
#   put 'profile', to: 'users#update', as: 'update_profile'
#   get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
#   get '/profile', to: 'users#show_profile', as: 'profile'







#   get '/bookings' => 'bookings#index', as: 'bookings'
#   post '/cars/:id/bookings' => 'bookings#create'
#   get '/bookings/:id' => 'bookings#show' , as: 'booking'
#   get '/bookings/:id/edit' => 'bookings#edit', as: 'edit_booking'
#   patch '/bookings/:id' => 'bookings#update'
#   delete '/bookings/:id' => 'bookings#destroy', as: 'return_booking'



#   get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'

#   get '/contactus' => 'ourcontacts#index' ,  as: 'contactus'

# get '/customers/:customer_id/bookings' => 'bookings#index', as: 'bookings_customers'
# post '/bookings/:id' => 'bookings#update'
# #post '/customers/:customer_id/bookings' => 'bookings#update'

# end

#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meal.rb
class Meal < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   belongs_to :user

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user
  helper_method :group_by_day


  def index

     @meals = Meal.where(user_id: current_user.id).order(date: :desc)
     p "========"
      p "========"
      p @meals
       p "========"
        p "========"

#       @date = meal_params[:date]

# Meal.select("date(created_at) as ordered_date, sum(price) as total_price").group("date(created_at)")
    # @type = @workouts.type
    # @description = @workouts.description
    # @date = @meals.date
  end

  def new
    @meals = Meal.all
    @meal_categories = MealCategory.all


  end

  def create
    foobar = meal_params()

    @meal = Meal.new(foobar)
    @meal.user = current_user
     # Pass in a date
      #if (customer_params[:lisence_expiry].to_date >  Date.today+14.days)


    if @meal.save
      redirect_to @meal
      else
        #byebug
      render 'new'
  end

end


  def show

  @meal = Meal.find(params[:id])
  @mealtype = @meal.meal_category.description


  end


  def edit

    @meal = Meal.find(params[:id])
     @meal.user = current_user
     @meal_categories = MealCategory.all

  end

  def update
    @meal = Meal.find(params[:id])
    redirect_to meal_path if @meal.update(meal_params)
  end

   def destroy

  @meal = Meal.find(params[:id])

         @meal.destroy
         redirect_to meals_path

  end

  private
    def check_user
      if !current_user
        redirect_to home_path
      end
    end

    def meal_params
      params.require(:meal).permit(:meal_category_id, :description, :calories, :date)
    end


    def group_by_day(obj)
      sort_by_day = -> ( d ) {d.start.strftime("%A, %b %d %y")}
      return obj.group_by(&sort_by_day)
    end


end

app/views/meals/edit.html.erb
<body class="mealeditbody">
	<div class="container">
<h1 class="mealeditheading">Edit Meal</h1>
<div class="mealeditform">
<%= form_with scope: :meal, model: @meal, local: true do |form| %>

   <p>
    <strong><%= form.label :type %><br></strong>
    <%= form.collection_select :meal_category_id, @meal_categories, :id, :description %>
  </p>

  <p>
    <strong><%= form.label :description %><br></strong>
    <%= form.text_area :description %>
  </p>

  <p>
    <strong><%= form.label :calories %><br></strong>
    <%= form.number_field :calories %>
  </p>

  <p>
    <strong><%= form.label :date %><br></strong>
    <%= form.date_field :date %>
  </p>
  <p>
    <%= form.submit class: "btn btn-dark"%>
  </p>

<% end %>
</div>
<div class ="backbutton">
<%= button_to 'Back', meal_path , method: :get, class:"btn btn-dark" %>
</div>
</div>
</body>

app/views/meals/index.html.erb
<body class="mealbody">
	<div class="container">

		<h3 class="mealheading">Meals List</h3>
		<%= button_to "Add meals", new_meal_path, method: :get, class: "btn btn-dark" %>
			<div class="mealtext">


				<% current_meals_per_date = @meals[0].date unless @meals.length == 0 %>
				<% calories_daily_total = 0 %>

				<% @meals.each do |meal| %>


				<% if current_meals_per_date != meal.date %>

					Calories Total: <%= calories_daily_total %>

					<% calories_daily_total = 0 %>

					<% current_meals_per_date = meal.date %>

				<%end %>

					<% calories_daily_total = meal.calories + calories_daily_total %>


										<table class="table table-dark">

	<thead>
    <tr>

      <th scope="col">Type</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">Calories</th>


    </tr>
  </thead>


  <tbody>
    <tr>

			<td><%= meal.meal_category.description.capitalize %></td>
      <td><%= meal.description %></td>
      <td><%= meal.date %></td>
      <td><%= meal.calories %></td>
      <td><button class="buttontextmeal"><%= link_to 'Details', meal_path(meal) , class:"btn btn-white" %></button></td>
    </tr>

  </tbody>
</table>



						</p>


				<% end %>
				<p>
					Calories Total: <%= calories_daily_total %>
				</p>
			</div>

	</div>

</body>

app/views/meals/new.html.erb
<body class="mealnewbody">
	<div class="container">

<h1 class="mealnewheading">Enter Your Meal</h1>
<div class="mealeditform">
<%= form_with scope: :meal, url: meals_path, local: true do |form| %>
  <p>
  <strong><%= form.label :type %></strong><br>
  <%= form.collection_select :meal_category_id, @meal_categories, :id, :description %>
  </p>

  <p>
    <strong><%= form.label :description %></strong><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <strong><%= form.label :calories %></strong><br>
    <%= form.number_field :calories %>

  </p>

  <p>
    <strong><%= form.label :date %></strong><br>
    <%= form.date_field :date %>

  </p>

  	<p class="savebutton">
	  <%= form.submit class: "btn btn-dark"%>
	</p>

<% end %>
</div>
<div class ="backbutton">
<%= button_to 'Back', meals_path , method: :get, class:"btn btn-dark" %>
</div>
</div>
</body>

app/views/meals/show.html.erb
<body class="mealbody">
	<div class = "container">
		<p class="mealtext">

		  <strong>Type:</strong>

		  <%= @mealtype.capitalize %>

		</p>

		<p class="mealtext">
		  <strong>Description:</strong>
		  <%= @meal.description.capitalize %>
		</p>

		<p class="mealtext">
		  <strong>Calories: </strong>
		  <%= @meal.calories %>
		</p>

		<p class="mealtext">
		  <strong>Date: </strong>
		  <%= @meal.date %>
		</p>


		<br/>
		<div class ="mealprofilebutton">
		<div class ="row-md">


		<div class ="column-md , profilesubbutton">


		<button class="btn btn-dark"><%= link_to 'Edit', update_meal_path , class:"buttontext" %></button>



		<button class="btn btn-dark"><%= link_to 'Home', home_path , class:"buttontext" %></button>

		<button class="btn btn-dark"><%= link_to 'Back', meals_path , class:"buttontext" %></button>



		<button class="btn btn-dark"><%= link_to 'Delete', meal_path,
		        method: :delete,
		        data: { confirm: 'Are you sure?' }  , class:"buttontext" %></button>

	</div>
	</div>

	</div>
	</div>
</body>