config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'onepage/index'
  root to: "onepage#index", as: 'home'



 get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'



  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile/:id/edit', to: 'users#edit', as: 'update_profile'
  patch '/profile/:id/edit', to: 'users#update', as: 'user'



  get '/workouts' => 'workouts#index', as: 'workouts'
  get '/workouts/new' => 'workouts#new', as: 'new_workout'
  post '/workouts' => 'workouts#create'
  get '/workout/:id/edit', to: 'workouts#edit', as: 'update_workout'
  patch '/workouts/:id', to: 'workouts#update'

  get '/workouts/:id' => 'workouts#show' , as: 'workout'
  delete '/workouts/:id' => 'workouts#destroy'




  get '/meals' => 'meals#index', as: 'meals'
  get '/meals/new' => 'meals#new', as: 'new_meal'
  post '/meals' => 'meals#create'

   get '/meal/:id/edit', to: 'meals#edit', as: 'update_meal'
  patch '/meals/:id', to: 'meals#update'

  get '/meals/:id' => 'meals#show' , as: 'meal'
  delete '/meals/:id' => 'meals#destroy'




  get '/tips' => 'tips#index', as: 'tips'
  get '/tips/new' => 'tips#new', as: 'new_tip'
  post '/tips' => 'tips#create'
  get '/tips/:id/edit', to: 'tips#edit', as: 'update_tip'
  patch '/tips/:id', to: 'tips#update'


  get '/tips/:id' => 'tips#show' , as: 'tip'
  delete '/tips/:id' => 'tips#destroy'






#   get '/meals/:id/bookings/new'=> 'bookings#new' ,as:'new_booking'
#   get '/meals/:id/edit' => 'meals#edit', as: 'edit_meal'
#   patch '/meals/:id' => 'meals#update'
#   delete '/meals/:id' => 'meals#destroy'


#   get '/users' => 'users#index', as: 'users'
#   get '/users/new' => 'users#new', as: 'new_user'
#   post '/users' => 'users#create'
#   get '/users/:id' => 'users#show' , as: 'user'
#   get '/users/:id/edit' => 'users#edit', as: 'edit_user'
#   patch '/users/:id' => 'users#update'
#   delete '/users/:id' => 'users#destroy'


#   get 'users/:id', to: 'users#show_profile'
#   get 'users/:id/edit', to: 'users#edit'
#   put 'profile', to: 'users#update', as: 'update_profile'
#   get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
#   get '/profile', to: 'users#show_profile', as: 'profile'







#   get '/bookings' => 'bookings#index', as: 'bookings'
#   post '/cars/:id/bookings' => 'bookings#create'
#   get '/bookings/:id' => 'bookings#show' , as: 'booking'
#   get '/bookings/:id/edit' => 'bookings#edit', as: 'edit_booking'
#   patch '/bookings/:id' => 'bookings#update'
#   delete '/bookings/:id' => 'bookings#destroy', as: 'return_booking'



#   get '/aboutus' => 'companyprofiles#index' , as: 'aboutus'

#   get '/contactus' => 'ourcontacts#index' ,  as: 'contactus'

# get '/customers/:customer_id/bookings' => 'bookings#index', as: 'bookings_customers'
# post '/bookings/:id' => 'bookings#update'
# #post '/customers/:customer_id/bookings' => 'bookings#update'

# end

#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tip.rb
class Tip < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   belongs_to :user


end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user




  def index

  @tips = Tip.where(user_id: current_user.id)

  end


  def new
    @tips = Tip.all

  end

  def create

      foobar = tip_params()

      @tip = Tip.new(foobar)
      @tip.user = current_user


      if @tip.save
        redirect_to @tip
        else
          #byebug
        render 'new'
    end

end


  def show

  @tip = Tip.find(params[:id])



  def edit

    @tip = Tip.find(params[:id])
     @tip.user = current_user


  end

  def update

    @tip = Tip.find(params[:id])

    redirect_to tip_path if @tip.update(tip_params)
  end



  end

 def destroy

  @tip = Tip.find(params[:id])

         @tip.destroy
         redirect_to tips_path

  end


    private
    def check_user
      if !current_user
        redirect_to home_path
      end
    end

    def tip_params
      params.require(:tip).permit(:description)


    end



end

app/views/tips/edit.html.erb
<body class="tipeditbody">
	<div class="container">
<h1 class="tipeditheading">Edit Tip</h1>
<div class="workouteditform">
<%= form_with scope: :tip, model: @tip, local: true do |form| %>


  <p>
    <strong><%= form.label :description %><br></strong>
    <%= form.text_area :description %>
  </p>



  <p>
    <%= form.submit class: "btn btn-dark"%>
  </p>

<% end %>
</div>
<div class ="backbutton">
<%= button_to 'Back', tip_path , method: :get, class:"btn btn-dark" %>
</div>
</div>
</body>

app/views/tips/index.html.erb
<body class="tipbody">
	<div class="container">
		<h3 class="tipheading">Tips</h3>
		<%= button_to "Add Tips", new_tip_path, method: :get, class: "btn btn-dark" %>
		<div class="tiptext">
			<table class="table table-dark">
				<thead>
  				<tr>
  					<th scope="col">#</th>
    				<th scope="col">Tips</th>
    			</tr>
				</thead>
				<tbody>
						<% @tips.each_with_index do |tip, index| %>
						<tr>
							<td class="tiplist">
	  							<%= index + 1 %>
	  					</td>
	  					<td class="tiplist">
	  							<%= tip.description %>
	  					</td>
	  					<td>
	  						<button class="buttontextmeal">
	  							<%= link_to 'details', tip_path(tip) , class: "btn btn-white" %>
	  						</button>
	  					</td>
 						</tr>
 					<% end %>
 				</tbody>
 			</table>
		</div>
	</div>
</body>

app/views/tips/new.html.erb
<body class="mealnewbody">
	<div class="container">

<h1 class="tipnewheading">Add Tip</h1>
<div class="tipnewform">

<%= form_with scope: :tip, url: tips_path, local: true do |form| %>


  <p>
    <strong><%= form.label :Tip %></strong><br>
    <%= form.text_area :description %>
  </p>


	<p>
	  <%= form.submit class: "btn btn-dark"%>
	</p>

<% end %>
</div>
<div class ="backbutton">
<%= button_to 'Back', tips_path , method: :get, class:"btn btn-dark" %>
</div>
</div>
</body>

app/views/tips/show.html.erb
<body class="mealnewbody">
	<div class = "container">

		<p class="tiptext">



		<p class="tiptext">
		  <strong>Description:</strong>
		  <%= @tip.description %>
		</p>





		<div class ="column-md , profilesubbutton">


		<button class="btn btn-dark"><%= link_to 'Edit', update_tip_path , class:"buttontext" %></button>



		<button class="btn btn-dark"><%= link_to 'Home', home_path , class:"buttontext" %></button>

		<button class="btn btn-dark"><%= link_to 'Back', tips_path , class:"buttontext" %></button>



		<button class="btn btn-dark"><%= link_to 'Delete', tip_path,
		        method: :delete,
		        data: { confirm: 'Are you sure?' }  , class:"buttontext" %></button>

	</div>
	</div>
	</div>
	</div>
	</div>
</body>